### ISSUE TITLE
Property match not exact

### ISSUE THREAD

**Issue by MoMannn** [cyrilschumacher/json-property-filter#5]
If I have a Json as such:

`{
 "test": "1",
  "test1": "3",
 "desc": "testing"
}`

And I filter as: `["test"]`

I will get result: 

`{
 "test": "1",
  "test1": "3"
}`

Meaning include does not do exact matching.

**Comment by cyrilschumacher** [comment]
Hello @MoMannn, I am rewriting the library and I plan to take your point in this new version.

**Comment by cyrilschumacher** [comment]
Fixed in the version: 2.0.0.
